services:
  - type: web
    name: digital-library
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn library_portal.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4